# Site
title:              Social Media Bot
bio:                'Social Media Bot'
description:        "Social Media Bot and Automation for SoundCloud, Twitter, Instagram, YouLikeHits, AddMeFast, and more"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/somiibo-logo-app.png'
background:         'assets/img/gradient-green-1.png'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://soundgrail.com
# url:                "http://127.0.0.1:4000"
trailing: "/"
enforce_ssl: soundgrail.com   # without any protocol
enforce_ssl: www.soundgrail.com   # without any protocol

price-premium-lifetime: "139.95"
price-premium-monthly: "5.95"
price-premium-yearly: "68.95"
price-repost-plus: "4.95"
price-repost-ultra: "9.95"
price-repost-supreme: "16.95"
price-plays-1000: "4.95"
price-plays-3000: "12.95"
price-plays-5000: "16.95"
price-promotion-track: "18.95"

default-lastmod: "2017-01-30T00:20:35+00:00"

includes:
- assets

collections:
  authors:
    title: Authors
    output: true

defaults:
- scope:
    path: ''
    type: authors
  values:
    permalink: "/team/:title/"
    layout: author
    twitter:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   somiibo

# Social
compress_html:
  clippings: [all]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old, xyz, building]
